baseURL = "https://xumf.net/"
title = "小蜜蜂"
theme = "stack"
defaultContentLanguage = "zh"
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 10

[permalinks]
post = "/blog/:slug/"
page = "/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true

[frontmatter]
  [frontmatter.defaults]
    [frontmatter.defaults.values]
      slug = "{{ .Name | urlize }}"

[taxonomies]
tag = "tags"
category = "categories"

[params]
mainSections = ["blog"]
description = "一个热爱技术、开朗积极的开发者的博客"

[params.footer]
since = 2018

[params.dateFormat]
published = "2006年 1月 02日"
lastUpdated = "2006年 1月 02日"

[params.sidebar]
subtitle = "Code Farming Engineer"
avatar = "/images/logo.png"
compact = false

[params.article]
headingAnchor = false
toc = true
readingTime = true

[params.article.list]
showTags = true

[params.widgets]
homepage = []
page = []

[params.colorScheme]
toggle = true
default = "auto"

[params.comments]
enabled = true
provider = "disqus"

[params.comments.disqusjs]
shortname = "xumf"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/xumf/"

[menu.social.params]
icon = "brand-github"

[[menu.main]]
identifier = "blog"
name = "博客"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 30

[services.disqus]
shortname = "xumf"

[services.googleAnalytics]
id = "UA-118288238-1"
